### ISSUE TITLE
can't find a function that changes the color of the entire room.

### ISSUE THREAD

**Issue by hoso3392** [autodesk-platform-services/aps-iot-extensions-demo#9]
I would like to change the color according to the temperature in each room unit, as presented in the following URL. 
https://aps.autodesk.com/en/docs/dataviz/v1/developers_guide/examples/heatmap/create_heatmap_for_rooms/

However, the code provided does not reflect the color change.(As of February 26, 2023)
Please let me know how I can make it reflect.

**Comment by yiskang** [comment]
Did you change the objectId of the sensors in the config.js? 

It represents the room dbids. Revit rooms are not visible in Revit 3D views, Model Derivative generates it by user-specified generated Master view option, so rooms’ dbids would be inconsistent in each SVF/SVF2 translation.

**Comment by yiskang** [comment]
> Thank you very much, I have not changed the value of the objectId in services/iot.mocked.js.
> 
> One thing I am wondering is what method can I use to get the value of APS_MODEL_VIEW that I need to specify in aps-iot-extensions-demo/public/config.js? Maybe I am not specifying the value correctly.

It's the Revit master view's `viewableID`. You can find it in the [manifest response](https://aps.autodesk.com/en/docs/model-derivative/v2/reference/http/manifest/urn-manifest-GET/).
